### ISSUE TITLE
How to use liff-mock in LIFF sdk v2.22.0

### ISSUE THREAD

**Issue by bathtimefish** [line/liff-mock#14]
I could not use liff-mock in LIFF sdk v2.22.0 pluggable mode.
https://developers.line.biz/en/docs/liff/pluggable-sdk/#pluggable-sdk-use-conditions

The following error occurred when I wrote the following code.

```App.tsx
import { useEffect, useState } from "react";
import liff from "@line/liff/core";
import "./App.css";
import { LiffMockPlugin } from '@line/liff-mock';

liff.use(new LiffMockPlugin());
```

```
ugin.js:15 Uncaught TypeError: liff.isInClient is not a function
    at LiffMockPlugin2.install (plugin.js:15:31)
    at Object.use (index.es.js:1:2110)
    at App.tsx:11:6
```

It seems that liff.use() don't support LiffMockPlugin.
In this case, how should I use liff-mock?

**Comment by cola119** [comment]
@bathtimefish Thank you for the report! It seems to be something wrong with LIFF Mock. Let me check.

**Comment by odanado** [comment]
@bathtimefish 
Our documentation was not sufficient.
Since liff-mock depends on isInClient, you must enable the LIFF API before you can use it in pluggable sdk.

```ts
import IsInClientModule from "@line/liff/is-in-client";
liff.use(new IsInClientModule());
```

**Comment by bathtimefish** [comment]
@odanado
Thank you for your update! I have confirmed that it works fine and I wrote a blog for it. (in Japanese)
https://qiita.com/bathtimefish/items/c03f53e4fdd39d48c891
