### ISSUE TITLE
Need this library work in typescript running on nodejs

### ISSUE THREAD

**Issue by bombxdev** [line/liff-mock#9]
Actually this library works well in typescript, but I still got some syntax error. 
 
**1) mock**
```
 Argument of type '{ liffId: string; mock: boolean; }' is not assignable to parameter of type 'Config'.
  Object literal may only specify known properties, and 'mock' does not exist in type 'Config'.ts(2345)
```
**2) $mock**
```
any
Property '$mock' does not exist on type 'Liff'.ts(2339)
```
**3) p IN liff.$mock.set((p)**
```
Parameter 'p' implicitly has an 'any' type.ts(7006)
```

Thank you in advance.

**Comment by cola119** [comment]
You need to prepare the type declaration for liff-mock to work with TypeScript by yourself.

https://github.com/line/liff-mock/blob/595106446515a8d68c885f38c8c9ec225fbf5588/examples/npm-typescript-example/src/liff.d.ts#L1-L8

Please refer to [TypeScript Example](https://github.com/line/liff-mock/tree/main/examples/npm-typescript-example)

**Comment by bombxdev** [comment]
> You need to prepare the type declaration for liff-mock to work with TypeScript by yourself.
> 
> https://github.com/line/liff-mock/blob/595106446515a8d68c885f38c8c9ec225fbf5588/examples/npm-typescript-example/src/liff.d.ts#L1-L8
> 
> Please refer to [TypeScript Example](https://github.com/line/liff-mock/tree/main/examples/npm-typescript-example)

It works :pray::pray::pray:
